# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Node.js CI

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.x, 16.x, 18.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build --if-present
#     - run: npm test

name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  check_out:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  build:
    runs-on: self-hosted

    steps:

      - name: Kill the running container with name ios-cra
        needs: check_out
        run: |
          docker stop ios-cra || true
          docker rm ios-cra || true

      - name: Build the Docker image
        run: |
          docker build -t ios-cra .

      - name: stop running container running on port 5173
        run: |
          docker stop $(docker ps | grep ':5173->' | awk '{ print $1 }') || true

      - name: Run Docker container
        run: |
          docker run --name ios-cra -p 5173:5173 -d ios-cra
